name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'
        cache: 'maven'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.8

    - name: Build with Maven
      run: mvn clean install

    - name: Build JavaDoc
      run: mvn -f azure-runtime/pom.xml clean javadoc:aggregate

    - name: Upload JavaDoc to Azure Blob Storage
      uses: bacongobbler/azure-blob-storage-upload@v3.0.0
      with:
        source_dir: 'azure-runtime/target/site/apidocs'
        container_name: '$web'
        connection_string: ${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}
        sync: 'true'